### ISSUE TITLE
HTVOnline api not accessible

### ISSUE THREAD

**Issue by anhstar** [traitravinh/traitravinh.repository.xbmc#2]
Chao ban, hinh nhu HTVOnline api khong con dung duoc nua thi phai? Addon toan bi loi khi bat.

**Comment by traitravinh** [comment]
vẫn chạy tốt mà.

**Comment by anhstar** [comment]
Cảm ơn bạn, sáng nay mình thử lại thì chạy ngon rồi. Dạo này người ta thay đổi gì đó ở trong server nên thỉnh thoảng không xem được.

**Comment by hoangngoc72007** [comment]
Bác có thể cho em xin nguyên cái đoạn requestdata post lên trang api được không em không học python nên không hiểu nó gủi lên nhưng gì. cảm ơn bác nhiều
